spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:~/test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false

jwt:
  secret: YHCqRdTwpNyLvop6yHZxroexVEeX3HA0WsVxHidXac=

springdoc:
  swagger-ui:
    operationsSorter: alpha

logging:
  level:
    org.hibernate.orm.connections.pooling: warn
    org.hibernate.engine.transaction.jta.platform.internal: warn
